# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-28 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sc_city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Patna', 'Patna'), ('Jodhpur', 'Jodhpur'), ('Rourkela', 'Rourkela'), ('Raipur', 'Raipur'), ('Jaipur', 'Jaipur'), ('Kota', 'Kota'), ('Visakhapatnam', 'Visakhapatnam'), ('Vijaynagram', 'Vijaynagram'), ('Sikar', 'Sikar'), ('Kolkata', 'Kolkata'), ('Jhunjhunu', 'Jhunjhunu'), ('Korba', 'Korba'), ('Muzaffarpur', 'Muzaffarpur'), ('Varanasi', 'Varanasi'), ('Bhagalpur', 'Bhagalpur')], max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='sc_state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Rajasthan', 'Rajasthan'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar'), ('Bengal', 'Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Orrisa', 'Orrisa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chhatissgarh', 'Chhatissgarh')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_city_sc',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Patna', 'Patna'), ('Jodhpur', 'Jodhpur'), ('Rourkela', 'Rourkela'), ('Raipur', 'Raipur'), ('Jaipur', 'Jaipur'), ('Kota', 'Kota'), ('Visakhapatnam', 'Visakhapatnam'), ('Vijaynagram', 'Vijaynagram'), ('Sikar', 'Sikar'), ('Kolkata', 'Kolkata'), ('Jhunjhunu', 'Jhunjhunu'), ('Korba', 'Korba'), ('Muzaffarpur', 'Muzaffarpur'), ('Varanasi', 'Varanasi'), ('Bhagalpur', 'Bhagalpur')], max_length=30),
        ),
    ]
